version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stats-service
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    container_name: db_stats_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
#  stats-db:
#    image: postgres:14-alpine

  ewm-service:
    build: ewm-main-service
    image: main_server_image
    container_name: main_server_container
    ports:
      - "8080:8080"